# Generated by Django 4.1.2 on 2022-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default=' ', upload_to='documentos'),
            preserve_default=False,
        ),
    ]
